{{- if eq (include "ratify.notationCertsProvidedByFiles" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-notation-certs
type: Opaque
stringData:
{{- range $index, $cert := .Values.notation.certs }}
  ratify{{ $index }}.crt: |
{{ $cert.cert | indent 4 }}
{{- end }}
{{- end }}

---
{{- if and (eq (include "ratify.tlsCertsProvided" .) "false") (not (lookup "v1" "Secret" .Release.Namespace (include "ratify.tlsSecretName" .))) (.Values.provider.tls.disableCertRotation) }}
{{- fail "You must provide a TLS certificate/key for Ratify to use or enable cert rotation to make Ratify generate and rotate its certificate/key."}}
{{- else if or (eq (include "ratify.tlsCertsProvided" .) "true") (and (eq (include "ratify.tlsCertsProvided" .) "false") (not (lookup "v1" "Secret" .Release.Namespace (include "ratify.tlsSecretName" .))) (not .Values.provider.tls.disableCertRotation))}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
data:
  {{ include "ratify.tlsSecret" . | nindent 2 }}
{{- end }}