version: 2

updates:
  # ---------- main branch (default target) ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "v2"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "v2"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "v2"

  - package-ecosystem: "docker"
    directory: "/httpserver"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "golang"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"
    labels:
      - "v2"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vscode/devcontainers/go"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"
    labels:
      - "v2"

  # ---------- release-1.4 branch ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v1-dev"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "v1"

  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v1-dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "v1"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "v1-dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "v1"

  - package-ecosystem: "docker"
    directory: "/httpserver"
    target-branch: "v1-dev"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "golang"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "v1"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    target-branch: "v1-dev"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vscode/devcontainers/go"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "v1"
