vulnerabilities:
  - id: CVE-2025-27403
    statement: Ratify's internal components are being flagged by it's own CVE. Internal go build versions for non-tagged commits use a lower semver tag which causes false positives.