version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - errorlint
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    staticcheck:
      checks:
        - "SA*"
        - "-SA1019"
        - "-QF*"
        - "-ST*"
        - "-S*"
