---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.ratify.dev
  resources:
  - executorpodstatuses
  - executors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.dev
  resources:
  - executorpodstatuses/status
  - executors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.dev
  resources:
  - executors/finalizers
  verbs:
  - update
