---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedstores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedkeymanagementproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedkeymanagementproviders/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedkeymanagementproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedverifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedverifiers/status
  verbs:
  - get
  - patch
  - update