{{- $dockerAuthMode := or .Values.dockerConfig .Values.registryCredsSecret -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ratify.fullname" . }}
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ratify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ratify.selectorLabels" . | nindent 8 }}
        {{- if ne .Values.azureWorkloadIdentity.clientId "" }}
        azure.workload.identity/use: "true"
        {{- end }}
      annotations:
        {{- if eq .Values.instrumentation.metricsType "prometheus" }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.instrumentation.metricsPort | quote }}
        {{- end }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if and .Values.provider.cache.enabled  (eq .Values.provider.cache.type "dapr") }}
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ include "ratify.fullname" . }}
        {{- if eq (lower .Values.logger.level) "debug" }}
        dapr.io/enable-api-logging: "true"
        {{- end }}
        {{- end }}
    spec:
      {{- if or .Values.azureWorkloadIdentity.clientId .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "ratify.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthPort }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthPort }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          command:
            - "/app/ratify"
          args:
            - "serve"
            - "--http"
            - ":6001"
            - "-c"
            - "/usr/local/ratify/config.json"
            - "--enable-crd-manager"
            - --cert-dir=/usr/local/tls
            {{- if (lookup "v1" "Secret" .Release.Namespace "gatekeeper-webhook-server-cert") }}
            - --ca-cert-file=usr/local/tls/client-ca/ca.crt
            {{- end }}
            - --cache-enabled={{ .Values.provider.cache.enabled }}
            - --cache-type={{ default "ristretto" .Values.provider.cache.type }}
            - --cache-name={{ default "dapr-redis" .Values.provider.cache.name }}
            - --cache-size={{ .Values.provider.cache.cacheSizeMb }}
            - --cache-ttl={{ .Values.provider.cache.ttl }}
            - --metrics-enabled={{ .Values.instrumentation.metricsEnabled }}
            - --metrics-type={{ .Values.instrumentation.metricsType }}
            - --metrics-port={{ .Values.instrumentation.metricsPort }}
            - --health-port=:{{ .Values.healthPort }}
          ports:
            - containerPort: 6001
            {{- if .Values.instrumentation.metricsEnabled }}
            - containerPort: {{ required "You must provide .Values.instrumentation.metricsPort" .Values.instrumentation.metricsPort }}
            {{- end }}
            - containerPort: {{ required "You must provide .Values.healthPort"  .Values.healthPort }}
              name: healthz
              protocol: TCP
          volumeMounts:             
            {{- if and .Values.cosign.enabled .Values.cosign.key }}
            - mountPath: "/usr/local/ratify-certs/cosign"
              name: cosign-certs
              readOnly: true
            {{- end }}
            - mountPath: "/usr/local/ratify"
              name: config
              readOnly: true
              {{- if $dockerAuthMode }}
            - mountPath: "/usr/local/docker"
              name: dockerconfig
              readOnly: true
              {{- end }}
            - mountPath: /usr/local/tls
              name: tls
              readOnly: true
            {{- if (lookup "v1" "Secret" .Release.Namespace "gatekeeper-webhook-server-cert") }}
            - mountPath: /usr/local/tls/client-ca
              name: client-ca-cert
              readOnly: true
            {{- end }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.logger.level }}
            - name: RATIFY_LOG_LEVEL
              value: {{ .Values.logger.level }}
          {{- end }}
          {{- if $dockerAuthMode }}
            - name: DOCKER_CONFIG
              value: "/usr/local/docker"
          {{- end }}
          {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
            - name: AZURE_TENANT_ID
              value: {{ .Values.azureManagedIdentity.tenantId }}
          {{- end }}
          {{- if and .Values.oras.authProviders.awsEcrBasicEnabled .Values.oras.authProviders.awsApiOverride.enabled }}
            {{- if and .Values.oras.authProviders.awsApiOverride.endpoint .Values.oras.authProviders.awsApiOverride.partition .Values.oras.authProviders.awsApiOverride.region }}
            - name: AWS_API_OVERRIDE_ENDPOINT
              value: {{ .Values.oras.authProviders.awsApiOverride.endpoint }}
            - name: AWS_API_OVERRIDE_PARTITION
              value: {{ .Values.oras.authProviders.awsApiOverride.partition }}
            - name: AWS_API_OVERRIDE_REGION
              value: {{ .Values.oras.authProviders.awsApiOverride.region }}
            {{- end }}
          {{- end }}
            - name: RATIFY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RATIFY_NAME
              value: {{ include "ratify.fullname" . }}
          {{- range $k, $v := .Values.featureFlags }}
            - name: {{ $k }}
              value: {{ $v | ternary 1 0 | quote }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if and .Values.cosign.enabled .Values.cosign.key }}
        - name: cosign-certs
          secret:
            secretName: {{ include "ratify.fullname" . }}-cosign-certificate
        {{- end }}
        {{- if $dockerAuthMode }}
        - name: dockerconfig
          secret:
            {{- if .Values.registryCredsSecret }}
            secretName: {{ .Values.registryCredsSecret }}
            {{- else }}
            secretName: {{ include "ratify.fullname" . }}-dockerconfig
            {{- end }}
            items:
              - key: .dockerconfigjson
                path: config.json
        {{- end }}        
        - name: config
          configMap:
            name: {{ include "ratify.fullname" . }}-configuration
        - name: tls
          secret:
            secretName: {{ include "ratify.fullname" . }}-tls
        {{- if (lookup "v1" "Secret" .Release.Namespace "gatekeeper-webhook-server-cert") }}
        - name: client-ca-cert
          secret:
            secretName: gatekeeper-webhook-server-cert
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

