{{- $fullname := include "ratify.fullname" . -}}
---
{{- if .Values.notationCert }} 
apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementProvider
metadata:
  name: {{$fullname}}-notation-inline-cert
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  type: inline
  parameters:
    contentType: certificate 
    value: {{ .Values.notationCert | quote }}
{{- end }}
---
{{-  range $i, $cert := .Values.notationCerts }}
apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementProvider
metadata:
  name: {{$fullname}}-notation-inline-cert-{{$i}}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  type: inline
  parameters:
    contentType: certificate
    value: {{ $cert | quote }}
---
{{- end }}
{{-  range $i, $key := .Values.cosignKeys }}
apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementProvider
metadata:
  name: {{$fullname}}-cosign-inline-key-{{$i}}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  type: inline
  parameters:
    contentType: key
    value: {{ $key | quote }}
---
{{- end }}