{{- if or .Values.azureWorkloadIdentity.clientId .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
  {{- if .Values.azureWorkloadIdentity.clientId }}
    azure.workload.identity/use: "true"
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "ratify.serviceAccountName" . }}
{{- end }}
