name: "Steps to restore trivy cache"
description: "Steps to restore Trivy cache under ~/.cache/trivy"

runs:
  using: "composite"
  steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore trivy cache directory
      uses: actions/cache/restore@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: ${{ github.workspace }}/.cache/trivy
        key: cache-trivy-${{ steps.date.outputs.date }}
    - name: Set up trivy cache directory
      run: |
        mkdir -p ~/.cache/trivy
        cp -r ${{ github.workspace }}/.cache/trivy/db ~/.cache/trivy
      shell: bash
