#!/usr/bin/env bash
##--------------------------------------------------------------------
#
# Copyright The Ratify Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
##--------------------------------------------------------------------
#
# AKS identity binding end-to-end test for the ratify gatekeeper provider.
#
# This test exercises the ACR "azure" credential provider in identity binding
# mode: instead of federating the projected service account token with Entra
# (workload identity), ratify exchanges the token directly against the cluster
# identity binding local authority for an AAD access token, which is then
# exchanged for an ACR refresh token used to pull image manifests and notation
# signatures. Notation verification itself uses an inline trust store so the test
# stays focused on the identity binding based registry authentication path.
#
##--------------------------------------------------------------------

set -o errexit
set -o nounset
set -o pipefail

SUFFIX=$(openssl rand -hex 2)
export GROUP_NAME="${GROUP_NAME:-ratify-ib-e2e-${SUFFIX}}"
export ACR_NAME="${ACR_NAME:-ratifyib${SUFFIX}}"
export AKS_NAME="${AKS_NAME:-ratify-ib-aks-${SUFFIX}}"
export USER_ASSIGNED_IDENTITY_NAME="${USER_ASSIGNED_IDENTITY_NAME:-ratify-ib-identity-${SUFFIX}}"
export LOCATION="${LOCATION:-westus2}"
export KUBERNETES_VERSION=${1:-1.30.6}
GATEKEEPER_VERSION=${2:-3.18.0}
export RATIFY_NAMESPACE=${3:-gatekeeper-system}
CERT_DIR=${4:-"${HOME}/ratify/certs"}

TAG="test${SUFFIX}"
REGISTRY="${ACR_NAME}.azurecr.io"

# Helm release name for the v2 gatekeeper provider chart. It is used as the
# fully-qualified name, and therefore also as the in-cluster service DNS name
# that the TLS certificate SAN must match.
RATIFY_RELEASE_NAME="ratify-gatekeeper-provider"
# Service account name authorized to use the managed identity via the identity
# binding RBAC created in scripts/create-azure-resources-identity-binding.sh
# (system:serviceaccount:${RATIFY_NAMESPACE}:ratify-admin).
export SERVICE_ACCOUNT_NAME="ratify-admin"

# When SKIP_CREATE_RESOURCES=1 the caller has already provisioned the cluster,
# managed identity, identity binding and ACR (and set GROUP_NAME/ACR_NAME/
# AKS_NAME/USER_ASSIGNED_IDENTITY_NAME accordingly). Useful for local iteration.
SKIP_CREATE_RESOURCES="${SKIP_CREATE_RESOURCES:-0}"

build_push_to_acr() {
  echo "Building and pushing the ratify-gatekeeper-provider image to ACR"
  docker build --progress=plain --no-cache \
    -f ./Dockerfile \
    -t "${REGISTRY}/test/ratify-gatekeeper-provider:${TAG}" .
  docker push "${REGISTRY}/test/ratify-gatekeeper-provider:${TAG}"
}

deploy_gatekeeper() {
  echo "deploying gatekeeper"
  make e2e-deploy-gatekeeper GATEKEEPER_VERSION=${GATEKEEPER_VERSION} GATEKEEPER_NAMESPACE="gatekeeper-system"
}

deploy_ratify() {
  echo "deploying the ratify-gatekeeper-provider (v2) with identity binding"
  local IDENTITY_CLIENT_ID
  IDENTITY_CLIENT_ID=$(az identity show --name ${USER_ASSIGNED_IDENTITY_NAME} --resource-group ${GROUP_NAME} --query 'clientId' -o tsv)
  local IDENTITY_TENANT_ID
  IDENTITY_TENANT_ID=$(az identity show --name ${USER_ASSIGNED_IDENTITY_NAME} --resource-group ${GROUP_NAME} --query 'tenantId' -o tsv)

  # Generate static TLS certificates whose SAN matches the provider service DNS
  # (${RATIFY_RELEASE_NAME}.${RATIFY_NAMESPACE}).
  ./scripts/generate-tls-certs.sh ${CERT_DIR} ${RATIFY_RELEASE_NAME} ${RATIFY_NAMESPACE}

  # Notation verification uses an inline trust store (the ratify-bats-test cert
  # generated by `make e2e-notation-setup`) so the test isolates the identity
  # binding based ACR authentication rather than AKV access.
  helm install ${RATIFY_RELEASE_NAME} \
    ./deployments/ratify-gatekeeper-provider --atomic \
    --namespace ${RATIFY_NAMESPACE} --create-namespace \
    --set image.repository=${REGISTRY}/test/ratify-gatekeeper-provider \
    --set image.tag=${TAG} \
    --set-file provider.tls.crt=${CERT_DIR}/server.crt \
    --set-file provider.tls.key=${CERT_DIR}/server.key \
    --set-file provider.tls.caCert=${CERT_DIR}/ca.crt \
    --set provider.tls.disableCertRotation=true \
    --set executor.scopes[0]=${REGISTRY}/notation \
    --set stores[0].scopes[0]=${REGISTRY}/notation \
    --set stores[0].credential.provider=azure \
    --set stores[0].credential.identityBinding.enabled=true \
    --set notation.scopes[0]=${REGISTRY}/notation \
    --set notation.certs[0].provider=inline \
    --set notation.certs[0].cert="$(cat ~/.config/notation/localkeys/ratify-bats-test.crt)" \
    --set serviceAccount.name=${SERVICE_ACCOUNT_NAME} \
    --set-string serviceAccount.annotations."azure\.workload\.identity/client-id"=${IDENTITY_CLIENT_ID} \
    --set-string serviceAccount.annotations."azure\.workload\.identity/tenant-id"=${IDENTITY_TENANT_ID}
}

save_logs() {
  echo "Saving logs"
  local LOG_SUFFIX="${KUBERNETES_VERSION}-${GATEKEEPER_VERSION}"
  kubectl logs -n gatekeeper-system -l control-plane=controller-manager --tail=-1 >logs-externaldata-controller-identity-binding-${LOG_SUFFIX}.json || true
  kubectl logs -n gatekeeper-system -l control-plane=audit-controller --tail=-1 >logs-externaldata-audit-identity-binding-${LOG_SUFFIX}.json || true
  kubectl logs -n ${RATIFY_NAMESPACE} -l app.kubernetes.io/name=ratify-gatekeeper-provider --tail=-1 >logs-ratify-gatekeeper-provider-identity-binding-${LOG_SUFFIX}.json || true
}

cleanup() {
  save_logs || true

  if [ "${SKIP_CLEANUP:-0}" = "1" ]; then
    echo "SKIP_CLEANUP=1, leaving resources in place"
    return
  fi

  echo "Deleting child resources (RG is shared, do not delete)"
  az aks      delete -g "${GROUP_NAME}" -n "${AKS_NAME}"                     --yes --no-wait || true
  az acr      delete -g "${GROUP_NAME}" -n "${ACR_NAME}"                     --yes           || true
  az identity delete -g "${GROUP_NAME}" -n "${USER_ASSIGNED_IDENTITY_NAME}"                  || true
}

trap cleanup EXIT

main() {
  if [ "${SKIP_CREATE_RESOURCES}" != "1" ]; then
    ./scripts/create-azure-resources-identity-binding.sh
  else
    echo "SKIP_CREATE_RESOURCES=1, using pre-provisioned cluster ${AKS_NAME}"
    az aks get-credentials --resource-group "${GROUP_NAME}" --name "${AKS_NAME}" --overwrite-existing
  fi

  local ACR_USER_NAME="00000000-0000-0000-0000-000000000000"
  local ACR_PASSWORD
  ACR_PASSWORD=$(az acr login --name ${ACR_NAME} --expose-token --output tsv --query accessToken)

  # Build and push the signed/unsigned notation test images to ACR and sign the
  # signed image with the ratify-bats-test certificate.
  make e2e-create-all-image e2e-notation-setup \
    TEST_REGISTRY=$REGISTRY \
    TEST_REGISTRY_USERNAME=${ACR_USER_NAME} \
    TEST_REGISTRY_PASSWORD=${ACR_PASSWORD}

  build_push_to_acr
  deploy_gatekeeper
  deploy_ratify

  TEST_REGISTRY=$REGISTRY bats -t ./test/bats/azure-identity-binding-test.bats
}

main
