name: build-pr

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions: read-all

jobs:
  call_test_e2e_basic:
    name: "run e2e on basic matrix"
    if: ${{ ! (contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'workflow_dispatch') }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.31.2"]
        GATEKEEPER_VERSION: ["3.18.0"]
    uses: ./.github/workflows/e2e-k8s.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}

  build_test_e2e_full_conditional:
    name: "run e2e on full test matrix with conditions"
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.30.6", "1.31.2"]
        GATEKEEPER_VERSION: ["3.16.0", "3.17.0", "3.18.0"]
    uses: ./.github/workflows/e2e-k8s.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}

  build_test_aks_e2e_conditional:
    name: "Build and run e2e Test on AKS with conditions"
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.35.5"]
        GATEKEEPER_VERSION: ["3.22.2"]
    uses: ./.github/workflows/e2e-aks.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}
    secrets: inherit
