name: e2e-aks

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      k8s_version:
        description: "Kubernetes version"
        required: true
        default: "1.31.2"
        type: string
      gatekeeper_version:
        description: "Gatekeeper version"
        required: true
        default: "3.18.0"
        type: string

jobs:
  build_test_aks_e2e:
    name: "Build and run e2e Test on AKS"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: azure-test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go 1.22
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "1.22"
      - name: Az CLI login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cache AAD tokens
        run: |
          az version
          # Key Vault: 
          az account get-access-token --scope https://vault.azure.net/.default --output none
          # Container Registry:
          az account get-access-token --scope https://containerregistry.azure.net/.default --output none

      - name: Restore Trivy cache
        uses: ./.github/actions/restore_trivy_cache

      - name: Dependencies e2e
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          make e2e-docker-credential-store-setup
          make e2e-dependencies

      - name: Run e2e on Azure
        run: |
          make e2e-aks KUBERNETES_VERSION=${{ inputs.k8s_version }} GATEKEEPER_VERSION=${{ inputs.gatekeeper_version }} TENANT_ID=${{ secrets.AZURE_TENANT_ID }} AZURE_SP_OBJECT_ID=${{ secrets.AZURE_SP_OBJECT_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: ${{ always() }}
        with:
          name: e2e-logs-aks-${{ inputs.k8s_version }}-${{ inputs.gatekeeper_version }}
          path: |
            logs-*.json
