name: publish-ghcr-and-chart

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_ref: ${{ steps.prepare.outputs.ref }}
      image_repository: ${{ steps.prepare.outputs.repository }}
      image_tag: ${{ steps.prepare.outputs.version }}
    permissions:
      packages: write
      contents: read
      id-token: write
    environment: azure-publish
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Notation
        uses: notaryproject/notation-action/setup@03242349f62aeddc995e12c6fbcea3b87697873f # v1.2.0
      - name: Install cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      - name: Az CLI login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cache AAD tokens
        run: |
          az version
          # Key Vault: 
          az account get-access-token --scope https://vault.azure.net/.default --output none
      - name: Prepare notation certificate
        run: |
          mkdir -p truststore/x509/ca/ratify-verify
          cp ./.well-known/pki-validation/ratify-verification.crt truststore/x509/ca/ratify-verify
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          REPOSITORY=ghcr.io/${{ github.repository }}
          REPOSITORYBASE=ghcr.io/${{ github.repository }}-base
          REPOSITORYCRD=ghcr.io/${{ github.repository }}-crds
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "repository=${REPOSITORY}" >> $GITHUB_OUTPUT
          echo "ref=${REPOSITORY}:${VERSION}" >> $GITHUB_OUTPUT
          echo "baseref=${REPOSITORYBASE}:${VERSION}" >> $GITHUB_OUTPUT
          echo "crdref=${REPOSITORYCRD}:${VERSION}" >> $GITHUB_OUTPUT
      - name: Get tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: docker login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build ratify-crds
        run: |
          docker buildx create --use
          docker buildx build \
            --attest type=sbom \
            --attest type=provenance,mode=max \
            --build-arg KUBE_VERSION="1.36.1" \
            -f crd.Dockerfile \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            -t ${{ steps.prepare.outputs.crdref }} \
            --push ./charts/ratify/crds
      - name: docker build ratify base
        run: |
          docker buildx create --use         
          docker buildx build -f ./httpserver/Dockerfile \
            --attest type=sbom \
            --attest type=provenance,mode=max \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg LDFLAGS="-X github.com/ratify-project/ratify/internal/version.Version=$TAG" \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            -t ${{ steps.prepare.outputs.baseref }} \
            --push .
      - name: docker build ratify with plugin
        run: |
          docker buildx create --use
          docker buildx build -f ./httpserver/Dockerfile \
            --attest type=sbom \
            --attest type=provenance,mode=max \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg build_sbom=true \
            --build-arg build_licensechecker=true \
            --build-arg build_schemavalidator=true \
            --build-arg build_vulnerabilityreport=true \
            --build-arg LDFLAGS="-X github.com/ratify-project/ratify/internal/version.Version=$TAG" \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            -t ${{ steps.prepare.outputs.ref }} \
            --push .
      - name: Sign with Notation
        uses: notaryproject/notation-action/sign@03242349f62aeddc995e12c6fbcea3b87697873f # v1.2.0
        with:
          plugin_name: azure-kv
          plugin_url: ${{ vars.AZURE_KV_PLUGIN_URL }}
          plugin_checksum: ${{ vars.AZURE_KV_CHECKSUM }}
          key_id: ${{ secrets.AZURE_KV_KEY_ID }}
          target_artifact_reference: |-
            ${{ steps.prepare.outputs.crdref }}
            ${{ steps.prepare.outputs.baseref }}
            ${{ steps.prepare.outputs.ref }}
          signature_format: cose
      - name: Sign with Cosign
        run: |
          cosign sign --yes ${{ steps.prepare.outputs.crdref }}
          cosign sign --yes ${{ steps.prepare.outputs.baseref }}
          cosign sign --yes ${{ steps.prepare.outputs.ref }}
      - name: Verify with Notation
        uses: notaryproject/notation-action/verify@03242349f62aeddc995e12c6fbcea3b87697873f # v1.2.0
        with:
          target_artifact_reference: |-
            ${{ steps.prepare.outputs.crdref }}
            ${{ steps.prepare.outputs.baseref }}
            ${{ steps.prepare.outputs.ref }}
          trust_policy: ./.well-known/pki-validation/trustpolicy.json
          trust_store: truststore
      - name: Verify with Cosign
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/notaryproject/ratify/.github/workflows/publish-package.yml@*" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-github-workflow-repository notaryproject/ratify \
            ${{ steps.prepare.outputs.crdref }}
          cosign verify \
            --certificate-identity-regexp "https://github.com/notaryproject/ratify/.github/workflows/publish-package.yml@*" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-github-workflow-repository notaryproject/ratify \
            ${{ steps.prepare.outputs.baseref }}
          cosign verify \
            --certificate-identity-regexp "https://github.com/notaryproject/ratify/.github/workflows/publish-package.yml@*" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-github-workflow-repository notaryproject/ratify \
            ${{ steps.prepare.outputs.ref }}
      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json

  e2e:
    name: Run e2e with published image and current chart
    needs: build
    uses: ./.github/workflows/e2e-k8s.yml
    with:
      k8s_version: "1.31.2"
      gatekeeper_version: "3.18.0"
      ratify_image_repository: ${{ needs.build.outputs.image_repository }}
      ratify_image_tag: ${{ needs.build.outputs.image_tag }}

  publish-chart:
    name: Publish Helm charts
    needs: e2e
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
