name: run-full-validation

on:
  pull_request:
    branches:
      - release-1.*
    paths-ignore:
      - "**.md"
  push:
    branches:
      - release-1.*
  workflow_dispatch:

permissions: read-all

jobs:
  call-e2e-cli:
    uses: ./.github/workflows/e2e-cli.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  call_test_e2e_full:
    name: "Build and run e2e on full test matrix"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.30.6", "1.31.2"]
        GATEKEEPER_VERSION: ["3.16.0", "3.17.0", "3.18.0"]
    uses: ./.github/workflows/e2e-k8s.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}
