name: target_branch_labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  label:
    name: Label PR by target branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Label based on target branch
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          sync-labels: true
